# Generated by Django 5.2.7 on 2025-12-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='blood_pressure',
            field=models.CharField(blank=True, help_text="Patient's blood pressure", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='blood_sugar',
            field=models.CharField(blank=True, help_text="Patient's blood sugar level", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature in °C', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
