# Generated by Django 5.2.7 on 2025-12-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient1', '0002_patienthistory_blood_pressure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienthistory',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='patienthistory',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='patienthistory',
            name='follow_up_date',
        ),
        migrations.RemoveField(
            model_name='patienthistory',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='patienthistory',
            name='prescribed_medications',
        ),
        migrations.RemoveField(
            model_name='patienthistory',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='patienthistory',
            name='treatment',
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Blood group', max_length=3, null=True),
        ),
    ]
